version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ai_bot_redis
    networks:
      - app-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  bot:
    build: .
    container_name: ai_bot
    networks:
      - app-network
    environment:
      - REDIS_URL=${REDIS_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
